README.md, docker-compose.yml, neo4j, neo4j-app/neo4j_app/__init__.py, neo4j-app/neo4j_app/app/utils.py, neo4j-app/neo4j_app/constants.py, neo4j-app/neo4j_app/core/config.py, neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/documents.py, neo4j-app/neo4j_app/core/neo4j/migrations/__init__.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrate.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrations.py, neo4j-app/neo4j_app/core/neo4j/named_entities.py, neo4j-app/neo4j_app/core/utils/pydantic.py, neo4j-app/neo4j_app/run/run.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrate.py, neo4j-app/neo4j_app/tests/run/test_run.py, src/main/java/org/icij/datashare/Neo4jResource.java, src/main/java/org/icij/datashare/Objects.java, src/test/java/org/icij/datashare/Neo4jResourceTest.java
This PR adds the ability to run migrations at the extension startup (this will be needed to add some indexes to `neo4j`).
Implemented a migration `neo4j.core.neo4j.migrate_db_schema` functions which has the following properties
- it takes a list of migration `Migration` objects which all have a `version`
- if fetches already run migrations from the `neo4j` DB
- based on the latest migration run on the DB it will try to run later migrations
- concurrent migrations are handle the following way:
- the `neo4j` DB has a `Migration` collection with uniqueness constraint on the `version`
- when a migration is selected as a candidate to be run against the DB the current thread will try to `CREATE` in with the `MigrationStatus.IN_PROGRESS` status
- because of the uniqueness constraint if any other …
=> feature: as a developer I should be able to migrate the `neo4j` DB

src/main/java/org/icij/datashare/Neo4jResource.java, src/main/java/org/icij/datashare/ProcessUtils.java, src/test/java/org/icij/datashare/Neo4jResourceTest.java, src/test/resources/shell_mock
This PR improves the management of the Python process lifecycle. In the current implementation, the Java application owns a Python process and try to kill the Python process when the extension closes. However if the extension crashes, it might not succeed to kill the process leaving a phantom Python process.
Additionnally some processing might be in progress on the Python side while closing the app.
This PR aims at decoupling the life of both processes.
- When calling `Neo4jResource.startServerProcess`, the extension now dumps the Python process PID in `/tmp`. When checking if the app is running, the extension now looks for the PID file in `/tmp`, if present, it will read the process ID and ask the OS for the process state. If the process is not alive the PID file is cleaned.
- Added …
=> chore: improve Python process lifecycle management

neo4j-app/neo4j_app/core/config.py, neo4j-app/neo4j_app/core/elasticsearch/client.py, neo4j-app/neo4j_app/core/imports.py, neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/documents.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrations.py, neo4j-app/neo4j_app/core/neo4j/named_entities.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrations.py, neo4j-app/pyproject.toml, src/main/java/org/icij/datashare/Neo4jResource.java
Leverage the work done in #18 in order to add uniqueness constraints and reduce incremental import by `x100`
- Added the `create_document_and_ne_id_unique_constraint_tx` migration to speed up document and named entities import time
- Added a `AppConfig.es_max_concurrency` in order to be able to configure the ES concurrency and speedup imports
=> chore: optimize incremental imports

neo4j-app/neo4j_app/app/documents.py, neo4j-app/neo4j_app/app/named_entities.py, neo4j-app/neo4j_app/constants.py, neo4j-app/neo4j_app/core/config.py, neo4j-app/neo4j_app/core/elasticsearch/client.py, neo4j-app/neo4j_app/core/elasticsearch/to_neo4j.py, neo4j-app/neo4j_app/core/imports.py, neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/documents.py, neo4j-app/neo4j_app/core/neo4j/imports.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrate.py, neo4j-app/neo4j_app/core/neo4j/named_entities.py, neo4j-app/neo4j_app/run/run.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrate.py, neo4j-app/neo4j_app/tests/core/neo4j/test_documents.py, neo4j-app/neo4j_app/tests/core/neo4j/test_imports.py, neo4j-app/neo4j_app/tests/core/neo4j/test_name_entities.py, neo4j-app/neo4j_app/tests/core/test_imports.py
Fixes #27
This PR avoids relying on the filesystem in order to perform incremental imports. The main reason for not relying on the filesystem it that we don't control the available disk space on the host machine and hence large import might fail.
Instead of exporting data from ES to CSV files, the incremental import are now performed fully in-memory in a "streaming" fashion.
The import was implemented with the following data points in mind:
- fetching data from ES is done in small pages (compared to the total import size)
- polling pages from ES is taking longer than inserting data into neo4j
- memory on the host machine is not unlimited, the size of the streaming buffer must be controlled
- ES, neo4j support concurrent import/export
The import was implemented using the producer-consumer …
=> chore: in-memory incremental import

neo4j-app/neo4j_app/core/config.py, neo4j-app/neo4j_app/core/utils/logging.py, neo4j-app/neo4j_app/run/run.py, neo4j-app/neo4j_app/tests/run/test_run.py
- Temporarily setup loggers in the main scripts before loggers are properly set using the logging config. This enables to log error even loggers have not been configure yet. This typically happens and invalid configuration is provided
=> chore: improve error handling before extension startup

neo4j-app/neo4j_app/app/admin.py, neo4j-app/neo4j_app/app/documents.py, neo4j-app/neo4j_app/app/named_entities.py, neo4j-app/neo4j_app/core/config.py, neo4j-app/neo4j_app/core/elasticsearch/client.py, neo4j-app/neo4j_app/core/imports.py, neo4j-app/neo4j_app/tests/app/test_admin.py, neo4j-app/neo4j_app/tests/app/test_documents.py, neo4j-app/neo4j_app/tests/app/test_named_entities.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/core/elasticsearch/test_client.py, neo4j-app/neo4j_app/tests/core/neo4j/test_imports.py, neo4j-app/neo4j_app/tests/core/neo4j/test_name_entities.py, neo4j-app/neo4j_app/tests/core/test_imports.py, neo4j-app/poetry.lock, neo4j-app/pyproject.toml, src/main/java/org/icij/datashare/Neo4jClient.java, src/main/java/org/icij/datashare/Neo4jResource.java, src/test/java/org/icij/datashare/Neo4jClientTest.java
While multiple project had been properly added on the `neo4j` side in #37, the extension was still setup to use a single index on the ES side and hence was not properly configuredfor a server usage. This PR adds a proper support of multiproject on the ES side.
- Forward the project `index` alongside the project `database` in `importNamedEntities`, `importDocuments` and `exportNeo4jCSVs`
- Removed the `AppConfig.neo4j_project` attribute
- Removed the `ESClient.project_index` attribute, the ES client now takes the index as method arguments
- Updated the `POST /neo4j-csvs`, `POST /documents`, `POST /named-entities` and underlying `neo4j.core.import` functions to take the ES index as input
=> fix: project support

neo4j-app/neo4j_app/core/config.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/core/test_config.py
The Python extension is performing some parsing of the ES address in order to separate the host and port  and provide them at the client initialization. This is not needed and done was the wrong way.
- Fixed the `ESClient` creation  by simply forwarding the provided ES address (which is properly handled by the client)
=> fix: es client creation

neo4j-app/neo4j_app/core/config.py
- limit ES log level to `INFO` at maximum to avoid polluting the logs
=> chore: limit ES level to `INFO` at maximum

neo4j-app/neo4j_app/app/utils.py, neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/migrations/__init__.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrate.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrate.py
When starting the application, the only the default DB was migrated which was not suitable when using the extension with the enterprise distribution and multiple projects.
- Renamed `migrate_db_schema` into `migrate_db_schemas` and migrate all neo4j databases
- For now the app will try to migrate all accessible DBs. More DBs are potentially found on the DB instance. A slight improvement to that brutal update could be to create a dedicated DB which name would be provided by config and reference all projects in that DB. This way only projects linked to this extension would be migrated
=> fix: migrate all projects

neo4j-app/neo4j_app/core/config.py
- Renamed `AppConfig.es_timeout: int` into `AppConfig.es_timeout_s: Union[int, float]` and forward it to the `ESClient`
=> fix: forward elasticsearch timeout

pom.xml, src/main/java/org/icij/datashare/HttpUtils.java, src/main/java/org/icij/datashare/Neo4jAppLoader.java, src/main/java/org/icij/datashare/Neo4jClient.java, src/main/java/org/icij/datashare/Neo4jResource.java, src/main/java/org/icij/datashare/ProcessUtils.java, src/test/java/org/icij/datashare/Neo4jAppLoaderTest.java, src/test/java/org/icij/datashare/Neo4jResourceTest.java, src/test/java/org/icij/datashare/ObjectsTest.java
Harmonize error handling in order to:
- log normalized messages
- return normalized HTTP errors
- avoid returning traces containing potential logs in http responses
- udpated `HttpError` to avoid deserializing the `trace` attribute, this way no trace information  will be returned by the HTTP. In order to be able to log message with traces a `HttpError.getMessageWithTrace()`  method was added
- removed inheritance between `Neo4jAppError` and `HttpError` to isolate their behavior. `Neo4jAppError` represents a error returned by the Python application, it serialization had not reason to be bound to the `HttpError` serialization/deserialization
- improved Java error handling by catching error locally and throwing detailed `RuntimeError`
- refactored `wrapNeo4jAppCall` to reformat any unhandled …
=> chore: harmonize error handling

src/main/java/org/icij/datashare/Neo4jClient.java, src/main/java/org/icij/datashare/Neo4jResource.java, src/test/java/org/icij/datashare/Neo4jResourceTest.java
Previously the Python app was marked as running as soon its port were open, in practice the app can take a little bit longer to respond
- `waitForServerToBeUp` now waits for the Python app to respond with a ping before marking the app as running
- fixed some flaky tests
=> fix: wait for python app to respond to mark extension as ready

src/main/java/org/icij/datashare/HttpUtils.java, src/main/java/org/icij/datashare/Neo4jResource.java, src/main/java/org/icij/datashare/Objects.java
This PR fixes in a quick and dirty manner a deserialization bug happening POSTing `DumpRequest` to the extension HTTP service.
The following payload is valid and correctly deserialized (if copy pasted in unit test)
```json
{
"format": "cypher-shell",
"query": {
"where": {
"startsWith": {
"property": {
"variable": "doc",
"name": "id"
},
"value": {
"literal": "somePrefix"
}
}
}
}
}
```
however when sending the payload through HTTP to the `POST /api/neo4j/dump` route, it results in a:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'org.icij.datashare.Neo4jUtils$VariableProperty' as a subtype of `org.icij.datashare.Neo4jUtils$VariableProperty`: Not a subtype
at [Source: (String)"{
"format": "cypher-shell",
"query": {
"where": { …
```
=> quickfix: fix payload deserialization error

neo4j-app/neo4j_app/core/elasticsearch/client.py
Following #91 it appeared that `_poll_scroll_search_pages` was still trying to use another `size` than the es default one. It didn't popped up in the test since most test run using a recent version of ES which polls using a PIT search rather than  a scrolled search.
- Remove `size` paramter from `_poll_scroll_search_pages`
=> fix: remove `size` from `_poll_scroll_search_pages`

neo4j-app/neo4j_app/core/elasticsearch/client.py, neo4j-app/neo4j_app/tests/core/test_imports.py
- Fixed potential `CancelledError` happening sometimes when there was no data to import, import workers were cancelled write away but still expected to complete their task
=> chore: exit early when tasks no data to import

src/main/java/org/icij/datashare/Neo4jResource.java
I was importing the  `Inject` annotation and also forgot to mark it as Singleton` which resulted in my `Neo4jResource` being recreated many times. I was seing it in the log but couldn't find the source of the bug...
- made `Neo4jResource` a guice singleton
- fixed the `Inject` annotation for `Neo4jResource`
=> fix: `Neo4jResource` dependency injection

neo4j-app/neo4j_app/constants.py, neo4j-app/neo4j_app/core/elasticsearch/to_neo4j.py, neo4j-app/neo4j_app/core/imports.py, neo4j-app/neo4j_app/core/neo4j/documents.py, neo4j-app/neo4j_app/core/neo4j/named_entities.py, neo4j-app/neo4j_app/tests/app/test_admin.py, neo4j-app/neo4j_app/tests/core/elasticsearch/test_to_neo4j.py, neo4j-app/neo4j_app/tests/core/neo4j/test_name_entities.py, neo4j-app/neo4j_app/tests/core/test_imports.py
This PR makes the most of work done in https://github.com/ICIJ/datashare/pull/1180 to import directed relationships for `:NamedEntity:EMAIL` when they are available.
Rather than implementing a new pipeline for email relationships, they are imported while importing `NamedEntity` inside the graph.
Modifying incremental imports was as simple as updating `core.neo4j.import_named_entity_rows` to create `:SENT`:`:RECEIVED` relationships based on `NamedEntity.metadata.emailHeader`
Updating admin import required a bit more work and updates inside the `core.import` module.
Two types of relationships were created
When the `NamedEntity.metadata.emailHeader` contains one of the following values:
- TODO
The following relationship is created:
```
(ne:NamedEntity:EMAIL { mentionNorm: "dev@icij.org" …
```
=> feature: email directed relationships

neo4j-app/neo4j_app/app/dependencies.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrate.py, neo4j-app/neo4j_app/core/neo4j/projects.py
When in enterprise support the default community DB called `neo4j` doesn't necessarily exist. Checking for the enterprise support has to be performed against the `system` DB which exists in both distributions.
For the same reason when the neo4j driver dependency is created, the piing on the DB has to performed on that same DB
- fixed ping and neo4j distribution detection when in enterprise distribution (using the `system` DB instead of the default DB)
=> fix: `neo4j` enterprise support

neo4j-app/neo4j_app/core/utils/pydantic.py, neo4j-app/neo4j_app/icij_worker/task.py, pom.xml, src/main/java/org/icij/datashare/Neo4jClient.java, src/main/java/org/icij/datashare/Neo4jResource.java, src/main/java/org/icij/datashare/Objects.java, src/test/java/org/icij/datashare/Neo4jClientTest.java, src/test/java/org/icij/datashare/Neo4jResourceTest.java
This PR updates the Java side of the extension with the work done in #101 so that tasks related operation (HTTP routes or CLI) can be built on the top of the `Neo4jResource`.
- replicated python objects into the java codebase `Task`, `TaskError`
- created the `TaskType` enum which will be used to define the task performed by the extension (only `FULL_IMPORT` for now)
- updated to the java `Neo4jClient` with task related methods
- implemented `neo4jResource.task`, `neo4jResource.taskResult`, `neo4jResource.taskErrors` which will be needed to build task related CLI and HTTP
- refactored `Neo4jClient` configuration
- replaced `checkExtensionProject` by `checkProject` which will additionally check that the project has been initiliazed
- python service dumps dates in a ISO format compatible …
=> feature: async tasks creation in java

src/main/java/org/icij/datashare/Neo4jClient.java, src/main/java/org/icij/datashare/Neo4jResource.java
Previously the `Neo4jClient` was using `Unirest.xxxxxxx` instead of wrapping a `UnirestInstance` instance.
This approaches caused test to be sometimes flaky when anything was happening to that single `UnirestInstance` instance (connection pool stop, disconnected or anything).
- refactor `Neo4jClient` to wrap a `UnirestInstance` instance and avoid using a global `UnirestInstance`
=> chore: refactor `Neo4jClient` to avoid using a global `UnirestInstance`

neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/graphs.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrations.py, neo4j-app/neo4j_app/tests/app/test_graphs.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrations.py, plugins/neo4j-graph-widget/components/WidgetNeo4jGraph.vue, plugins/neo4j-graph-widget/core/CoreExtension.js, src/main/java/org/icij/datashare/HttpUtils.java, src/main/java/org/icij/datashare/Neo4jResource.java, src/main/java/org/icij/datashare/Neo4jResourceWeb.java, src/main/java/org/icij/datashare/Objects.java, src/test/java/org/icij/datashare/Neo4jResourceWebTest.java
This PR fixes the export behavior of the graph. Previously the graph was streamed to the frontend but later put inside a `Blob` linked to a hidden button which was then clicked.
However to create the `Blob` the whole stream was consumed on the client side and hence the download started only after everything was read from the backend, which could be several minutes later.
The PR fixes this behavior by posting the dump request through an HTTP form opened in another blank tab (and without creating any `Blob`).
Additionnally the PR adds a few optimizations to make the export faster.
- changed `WidgetNeo4jGraph` to stream the dump by submitting on a hidden form which opens in new blank tab
- added indexes on `Document.path` and `Document.contentType` to make the export query faster
- adapted …
=> fix: export stream

neo4j-app/neo4j_app/constants.py, neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrations.py, neo4j-app/neo4j_app/core/neo4j/named_entities.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrations.py, neo4j-app/neo4j_app/tests/core/neo4j/test_name_entities.py
This PR adds the email domain and user to the graph nodes.
Email nodes will now look like: `:NAMED_ENTITY:EMAIL {mentionNorm: 'some-user@domain.com', emailUser: 'some-user', emailDomain: 'domain.com' , ...}`
The addition was done to let use build searches based on email domains / user names, which has been useful in the past.
- added `emailUser` and `emailDomain` properties to the `EMAIL` nodes (also added indexes on these properties)
=> feature: add email addresses domain and user in neo4j the graph

neo4j-app/neo4j_app/tests/app/test_admin.py, neo4j-app/neo4j_app/tests/app/test_graphs.py, neo4j-app/neo4j_app/tests/app/test_projects.py, neo4j-app/neo4j_app/tests/core/elasticsearch/test_client.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrate.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrations.py, neo4j-app/neo4j_app/tests/core/neo4j/test_documents.py, neo4j-app/neo4j_app/tests/core/neo4j/test_graphs.py, neo4j-app/neo4j_app/tests/core/neo4j/test_imports.py, neo4j-app/neo4j_app/tests/core/neo4j/test_name_entities.py, neo4j-app/neo4j_app/tests/core/neo4j/test_projects.py, neo4j-app/neo4j_app/tests/core/test_imports.py, neo4j-app/neo4j_app/tests/core/utils/test_asyncio.py, neo4j-app/neo4j_app/tests/core/utils/test_progress.py, neo4j-app/neo4j_app/tests/icij_worker/task_manager/test_neo4j.py, neo4j-app/neo4j_app/tests/icij_worker/worker/event_publisher/test_neo4j.py, neo4j-app/neo4j_app/tests/icij_worker/worker/test_neo4j.py, neo4j-app/neo4j_app/tests/icij_worker/worker/test_worker.py, neo4j-app/pyproject.toml
- remove `@pytest.mark.asyncio` decorators in favor of global `pytest` asyncio configuration through `asyncio_mode = "auto"` in `tool.pytest.ini_options` of the `pyproject.toml`
=> chore: automatically detect async tests

neo4j-app/neo4j_app/core/neo4j/migrations/migrate.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrate.py
Migration are always rerunning at app startup because the list of already run migrations was not done from the proper DB
- read already run migrations from the registry DB
=> fix: re-running migrations

neo4j
- remove linting tests from python tests (`./neo4j test -p neo4j_app`) as they are run with `./neo4j format_test -p neo4j_app`
=> fix: don't run linting test twice in CI

.data/datashare.properties.template
- use `bolt` as neo4j URI scheme for development as neo4j is not running in a cluster
=> chore: use bolt as neo4j URI scheme

neo4j-app/neo4j_app/core/config.py, neo4j-app/poetry.lock, neo4j-app/pyproject.toml, src/main/java/org/icij/datashare/Neo4jResource.java, src/main/java/org/icij/datashare/Neo4jResourceCli.java, src/test/java/org/icij/datashare/Neo4jResourceWebTest.java
Improve Python process logging.
Previously the Python process was not logging until the config was correctly loaded and the FastAPI server was up. This was preventing to log when:
- the config is wrong
- the FastAPI server failed to start (when any of the injected dependencies failed to be injected, neo4j not available for instance)
- added the ability redirected Python process output to Java process output
- added the ability for the Python process to log in JSON format which should help log collection and analysis by tools such as Loki, DataDog and so on
=> chore: improve Python process logging

neo4j-app/neo4j_app/app/dependencies.py, neo4j-app/neo4j_app/app/main.py, neo4j-app/neo4j_app/core/config.py, neo4j-app/neo4j_app/core/elasticsearch/client.py, neo4j-app/neo4j_app/icij_worker/exceptions.py, neo4j-app/neo4j_app/icij_worker/worker/process.py, neo4j-app/neo4j_app/icij_worker/worker/worker.py, neo4j-app/neo4j_app/run/run.py, neo4j-app/neo4j_app/tasks/app.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/core/test_config.py, neo4j-app/neo4j_app/tests/icij_worker/worker/conftest.py, neo4j-app/neo4j_app/tests/icij_worker/worker/test_process.py, neo4j-app/neo4j_app/tests/icij_worker/worker/test_worker.py, neo4j-app/neo4j_app/tests/icij_worker/worker/worker_main.py, neo4j-app/poetry.lock, neo4j-app/pyproject.toml
Improve the Python worker processes management to allow for clean shutdown.
When shutting down the HTTP server process sometimes was not allowing the Python async worker `multiprocessing.Pool`
This flaky behavior was potentially caused by:
- `multiprocessing.Pool.terminate()` hanging (potentially due to https://github.com/python/cpython/pull/8009)
- an unreliable `WorkerCancelled` exception thrown during `SIGTERM` and `SIGINT` in the hope to cancel the async worker. Throwing exceptions during signal handling [is not recommended](https://docs.python.org/3/library/signal.html#note-on-signal-handlers-and-exceptions)
- `uvicorn` not properly propagating signals to children processes they [recommend using Gunicorn](https://www.uvicorn.org/deployment/#gunicorn) for a cleaner management of …
=> fix: hanging Python async workers

neo4j-app/neo4j_app/app/dependencies.py
- remove the creation of the legacy worker pool in favor of the `ProcessPoolExecutor` (it was not removed when the executor was added)
=> fix: remove useless `multiprocessing.Pool` created for nothing

neo4j-app/neo4j_app/icij_worker/worker/worker.py, neo4j-app/neo4j_app/tests/icij_worker/worker/test_worker.py
In the current setup errors are saved only after the task has been `negatively_acknowledge`d. This leads to inconsistent state where the task can appear as `ERROR` while `TaskManager.get_task_errors` returns no error.
- simplified error handling and `negatively_acknowledge` tasks only after their errors have been saved
=> fix: negatively acknowledge error only after it has been saved

neo4j-app/neo4j_app/icij_worker/worker/worker.py
Failing tasks could be nacked twice as `Worker._current` was not reset to `None` after acking or nacking a task.
When the worker was shutdown after working, the worker was trying to requeue the task.
- set `Worker._current = None` right after acking or nacking tasks
=> fix: don't nack already nacked tasks

neo4j-app/neo4j_app/app/tasks.py, neo4j-app/neo4j_app/constants.py, neo4j-app/neo4j_app/core/elasticsearch/to_neo4j.py, neo4j-app/neo4j_app/core/imports.py, neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/documents.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrations.py, neo4j-app/neo4j_app/tests/app/test_tasks.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrate.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrations.py, neo4j-app/neo4j_app/tests/core/neo4j/test_documents.py, neo4j-app/neo4j_app/tests/core/test_imports.py, neo4j-app/pyproject.toml
Adding document nodes `createdAt` and `modifiedAt` attributes (attribute names chosen to match the follow the money schema). These attributes are read from ES document metadata.
While reading the ES metadata, we look for the DC terms created/modified metadata in priority since it's the one used in the `datashare-api` to define the `Docuemnt.getCreationDate()` (`tika_metadata_dcterms_modified`).  In case these metadata are not found we fallback to other tika metadata.
The fallback order to creation date is : 
- `tika_metadata_dcterms_created_iso8601`
- `tika_metadata_creation_date_iso8601`
- `tika_metadata_date_iso8601` 
for modification date it is:
- `tika_metadata_dcterms_modified_iso8601`
- `tika_metadata_last_modified_iso8601`
- `tika_metadata_modified_iso8601`
- …
=> feature: add document nodes create at and modified at attributes

neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrate.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrations.py, neo4j-app/neo4j_app/core/neo4j/named_entities.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrate.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrations.py, neo4j-app/neo4j_app/tests/core/neo4j/test_name_entities.py, neo4j-app/neo4j_app/tests/core/test_imports.py
- added the ability to use explicit transactions as migrations
- compute `NamedEntity.mentionCount` based on `mentionIds` instead of `offsets`
=> fix: support explicit transactions in migrations and fix mention count

neo4j-app/neo4j_app/constants.py, neo4j-app/neo4j_app/core/elasticsearch/to_neo4j.py, neo4j-app/neo4j_app/core/neo4j/documents.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/core/elasticsearch/test_to_neo4j.py, neo4j-app/neo4j_app/tests/core/neo4j/test_documents.py, neo4j-app/neo4j_app/tests/core/test_imports.py
Add title to `Document` nodes.
Document titles are read from ES metadata and  computed similarly as in the [datashare-client `DocumentView`](https://github.com/ICIJ/datashare-client/blob/master/src/pages/DocumentView.vue) and then added to imported document nodes.
- updated the regular and admin imports to add `title` to `Document` nodes
=> feature: add titles to documents

neo4j-app/neo4j_app/icij_worker/worker/worker.py, neo4j-app/neo4j_app/tests/icij_worker/worker/test_worker.py
- fixed  a bug where the worker was trying to exit on fatal errors
=> fix: worker should not shutdown on fatal error

neo4j-app/neo4j_app/icij_worker/worker/worker.py
- misleading success log in worker
=> fix: misleading success log in worker

neo4j-app/neo4j_app/icij_worker/__init__.py, neo4j-app/neo4j_app/icij_worker/utils/from_config.py, neo4j-app/neo4j_app/icij_worker/utils/registrable.py, neo4j-app/neo4j_app/icij_worker/worker/__init__.py, neo4j-app/neo4j_app/icij_worker/worker/config.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/icij_worker/utils/test_registerable.py, neo4j-app/neo4j_app/tests/icij_worker/worker/test_config.py
Add a `WorkerConfig` class which will be later used to create workers from a configuration file, environment variables or code.
The `Worker` and `WorkerConfig` will need to follow the [registry pattern](https://charlesreid1.github.io/python-patterns-the-registry.html) in order to be able to initialize any kind of worker implementation from an "unidentified" config.
This in turn will help implementing this kind of CLI:
```
icij_worker start async-app-name --worker-config config.json -n 4
```
Above, "unidentified" means that the caller code doesn't know more about the config than it's a `WorkerConfig`. The caller doesn't know which implementation of `Worker` it's supposed to instanciate.
Given
```python
class SomeWorkerConfig(WorkerConfig):
name: "some_worker_type"
... …
```
=> feature: define `WorkerConfig`

neo4j-app/neo4j_app/core/elasticsearch/client.py, neo4j-app/neo4j_app/tests/core/test_imports.py
The bug was not detecting in integration test since no progress was used in them.
- fix count queries for ES version supporting the PIT API
=> fix: count queries for ES `>= 7.14`

neo4j-app/neo4j_app/app/graphs.py, neo4j-app/neo4j_app/constants.py, neo4j-app/neo4j_app/core/elasticsearch/client.py, neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/graphs.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrate.py, neo4j-app/neo4j_app/core/neo4j/migrations/migrations.py, neo4j-app/neo4j_app/core/objects.py, neo4j-app/neo4j_app/tasks/imports.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/core/neo4j/migrations/test_migrations.py, neo4j-app/neo4j_app/tests/core/neo4j/test_graphs.py
Previously graph statistic computation was perform each time the client was asking for it (each time the project page was loaded).
Graph stats computation has already been optimized in the passed and reached a optimum, while still being too long to be computed on the fly.
The async import pipeline was updated to compute graph counts at the end of the import and stored the count in a singleton neo4j node containing the whole project stats.
When the client asks for graph stats, the python backend now just read this singleton node, whic enables to display counts immediatly:
https://github.com/ICIJ/datashare-extension-neo4j/assets/4267202/616de687-7d32-4452-a0dc-283fb58965a2
- updated the `full-import` task to refresh graph stats at the end of the import by storing them into a singleton node …
=> chore: optimize graph stats computation by making them asynchronous

neo4j-app/neo4j_app/core/elasticsearch/to_neo4j.py, neo4j-app/neo4j_app/core/neo4j/__init__.py, neo4j-app/neo4j_app/core/neo4j/documents.py, neo4j-app/neo4j_app/core/neo4j/migrations.py, neo4j-app/neo4j_app/tests/conftest.py, neo4j-app/neo4j_app/tests/core/neo4j/test_documents.py, neo4j-app/neo4j_app/tests/core/neo4j/test_migrations.py
Remove the following useless information:
- remove `:HAS_PARENT` self loop relationships
=> fix: remove useless `:HAS_PARENT` relationship

neo4j-app/neo4j_app/app/tasks.py, neo4j-app/neo4j_app/tests/conftest.py, plugins/neo4j-graph-widget/components/WidgetNeo4jGraph.vue
A user reported that the plugin was not behaving correctly: while the neo4j Python app was running and the graph was not created yet, the export button was available however the create graph button was not
This bug was the combination of a python (missing import button not to be available) and a wrong behavior on the frontend side (export button enabled while the graph is empty)
- fixed missing `TRACE` import 
- display the graph download button only when the graph is available and non empty for the project
=> fix: broken TRACE import and freeze download button when graph is empty
